import type {
  ActionMetric,
  ActionPlan,
  DepartmentResultKpi,
  EmployeeExecution,
  Kpi,
  KpiActual,
  KpiFormula,
  KpiTarget,
  Task,
} from "@/types/domain";
import { DEMO_COMPANY_ID, demoDepartments } from "@/lib/queries/demo";

export const executionDemoKpis: Kpi[] = [
  {
    id: "kpi_reviews_company_2026_04",
    company_id: DEMO_COMPANY_ID,
    code: "REVIEWS.COMPANY",
    name: "Tong danh gia 5 sao toan cong ty",
    description: "Result KPI tong hop cap cong ty cho review 5 sao trong thang 4/2026.",
    level: "company",
    owner_employee_id: "e1",
    owner_department_id: null,
    owner_team_id: null,
    unit: "reviews",
    weight: 1,
    parent_kpi_id: null,
    data_source: "manual_import",
    active: true,
    target_frequency: "monthly",
    calc_mode: "sum",
  },
  {
    id: "kpi_sla_company_2026_04",
    company_id: DEMO_COMPANY_ID,
    code: "SLA.COMPANY",
    name: "SLA phan hoi toan cong ty",
    description: "Ty le phan hoi dung SLA tong hop tu cac phong ban.",
    level: "company",
    owner_employee_id: "e1",
    owner_department_id: null,
    owner_team_id: null,
    unit: "%",
    weight: 1,
    parent_kpi_id: null,
    data_source: "third_party_platform",
    active: true,
    target_frequency: "monthly",
    calc_mode: "ratio",
  },
  {
    id: "kpi_reviews_sales_2026_04",
    company_id: DEMO_COMPANY_ID,
    code: "REVIEWS.SALES",
    name: "Danh gia 5 sao tu khach sau mua",
    description: "Result KPI cua Sales cho nhom khach vua mua hang.",
    level: "department",
    owner_employee_id: "e4",
    owner_department_id: "d001",
    owner_team_id: null,
    unit: "reviews",
    weight: 1,
    parent_kpi_id: "kpi_reviews_company_2026_04",
    data_source: "manual_import",
    active: true,
    target_frequency: "monthly",
    calc_mode: "sum",
  },
  {
    id: "kpi_reviews_ops_2026_04",
    company_id: DEMO_COMPANY_ID,
    code: "REVIEWS.OPS",
    name: "Danh gia 5 sao sau giao hang",
    description: "Result KPI cua Operations cho trai nghiem giao hang.",
    level: "department",
    owner_employee_id: "e6",
    owner_department_id: "d003",
    owner_team_id: null,
    unit: "reviews",
    weight: 1,
    parent_kpi_id: "kpi_reviews_company_2026_04",
    data_source: "manual_import",
    active: true,
    target_frequency: "monthly",
    calc_mode: "sum",
  },
  {
    id: "kpi_reviews_cskh_2026_04",
    company_id: DEMO_COMPANY_ID,
    code: "REVIEWS.CSKH",
    name: "5.000 danh gia 5 sao - dong CSKH",
    description: "Result KPI cap phong ban cho CSKH. Actual lay tu import tong, khong cong tu task.",
    level: "department",
    owner_employee_id: "e7",
    owner_department_id: "d004",
    owner_team_id: null,
    unit: "reviews",
    weight: 1,
    parent_kpi_id: "kpi_reviews_company_2026_04",
    data_source: "manual_import",
    active: true,
    target_frequency: "monthly",
    calc_mode: "sum",
  },
  {
    id: "kpi_sla_ops_2026_04",
    company_id: DEMO_COMPANY_ID,
    code: "SLA.OPS",
    name: "SLA xu ly giao van",
    description: "Ty le don duoc xu ly dung SLA cua Operations.",
    level: "department",
    owner_employee_id: "e6",
    owner_department_id: "d003",
    owner_team_id: null,
    unit: "%",
    weight: 1,
    parent_kpi_id: "kpi_sla_company_2026_04",
    data_source: "third_party_platform",
    active: true,
    target_frequency: "monthly",
    calc_mode: "ratio",
  },
  {
    id: "kpi_sla_cskh_2026_04",
    company_id: DEMO_COMPANY_ID,
    code: "SLA.CSKH",
    name: "SLA phan hoi CSKH",
    description: "Ty le phan hoi dung SLA cua team CSKH.",
    level: "department",
    owner_employee_id: "e7",
    owner_department_id: "d004",
    owner_team_id: null,
    unit: "%",
    weight: 1,
    parent_kpi_id: "kpi_sla_company_2026_04",
    data_source: "third_party_platform",
    active: true,
    target_frequency: "monthly",
    calc_mode: "ratio",
  },
];

const period = "2026-04";

export const executionDemoKpiTargets: KpiTarget[] = [
  { kpi_id: "kpi_reviews_company_2026_04", period, target_value: 5_000 },
  { kpi_id: "kpi_sla_company_2026_04", period, target_value: 95 },
  { kpi_id: "kpi_reviews_sales_2026_04", period, target_value: 1_800 },
  { kpi_id: "kpi_reviews_ops_2026_04", period, target_value: 1_200 },
  { kpi_id: "kpi_reviews_cskh_2026_04", period, target_value: 2_000 },
  { kpi_id: "kpi_sla_ops_2026_04", period, target_value: 95 },
  { kpi_id: "kpi_sla_cskh_2026_04", period, target_value: 95 },
];

export const executionDemoKpiActuals: KpiActual[] = [
  { kpi_id: "kpi_reviews_company_2026_04", period, actual_value: 3_200, completion_rate: 0.64, status: "yellow" },
  { kpi_id: "kpi_sla_company_2026_04", period, actual_value: 91, completion_rate: 91 / 95, status: "yellow" },
  { kpi_id: "kpi_reviews_sales_2026_04", period, actual_value: 1_220, completion_rate: 1_220 / 1_800, status: "yellow" },
  { kpi_id: "kpi_reviews_ops_2026_04", period, actual_value: 760, completion_rate: 760 / 1_200, status: "yellow" },
  { kpi_id: "kpi_reviews_cskh_2026_04", period, actual_value: 1_220, completion_rate: 1_220 / 2_000, status: "yellow" },
  { kpi_id: "kpi_sla_ops_2026_04", period, actual_value: 89, completion_rate: 89 / 95, status: "yellow" },
  { kpi_id: "kpi_sla_cskh_2026_04", period, actual_value: 92, completion_rate: 92 / 95, status: "yellow" },
];

export const executionDemoKpiFormulas: KpiFormula[] = [];

export const executionDemoDepartmentResultKpis: DepartmentResultKpi[] = [
  {
    id: "kpi_reviews_sales_2026_04",
    name: "Danh gia 5 sao tu khach sau mua",
    department_id: "d001",
    department_name: "Sales",
    period,
    type: "result_kpi",
    unit: "reviews",
    target: 1_800,
    actual: 1_220,
    data_source: "manual_import",
    rollup_mode: "manual",
    status: "yellow",
    days_left: 10,
    last_updated_at: "2026-04-20T16:10:00Z",
  },
  {
    id: "kpi_reviews_ops_2026_04",
    name: "Danh gia 5 sao sau giao hang",
    department_id: "d003",
    department_name: "Operations",
    period,
    type: "result_kpi",
    unit: "reviews",
    target: 1_200,
    actual: 760,
    data_source: "manual_import",
    rollup_mode: "manual",
    status: "yellow",
    days_left: 10,
    last_updated_at: "2026-04-20T16:20:00Z",
  },
  {
    id: "kpi_reviews_cskh_2026_04",
    name: "5.000 danh gia 5 sao - dong CSKH",
    department_id: "d004",
    department_name: "Customer Success",
    period,
    type: "result_kpi",
    unit: "reviews",
    target: 2_000,
    actual: 1_220,
    data_source: "manual_import",
    rollup_mode: "manual",
    status: "yellow",
    days_left: 10,
    last_updated_at: "2026-04-20T17:30:00Z",
  },
  {
    id: "kpi_sla_ops_2026_04",
    name: "SLA xu ly giao van",
    department_id: "d003",
    department_name: "Operations",
    period,
    type: "result_kpi",
    unit: "%",
    target: 95,
    actual: 89,
    data_source: "third_party_platform",
    rollup_mode: "third_party",
    status: "yellow",
    days_left: 10,
    last_updated_at: "2026-04-20T16:35:00Z",
  },
  {
    id: "kpi_sla_cskh_2026_04",
    name: "SLA phan hoi CSKH",
    department_id: "d004",
    department_name: "Customer Success",
    period,
    type: "result_kpi",
    unit: "%",
    target: 95,
    actual: 92,
    data_source: "third_party_platform",
    rollup_mode: "third_party",
    status: "yellow",
    days_left: 10,
    last_updated_at: "2026-04-20T18:00:00Z",
  },
];

export const executionDemoActionPlans: ActionPlan[] = [
  {
    id: "ap_sales_review_request",
    linked_kpi_id: "kpi_reviews_sales_2026_04",
    title: "Kich hoat review sau mua cho don moi",
    description: "Sales nhac review ngay sau khi khach nhan hang va xac nhan hai long.",
    owner_id: "e4",
    department_id: "d001",
    period,
    status: "active",
    expected_impact_text: "Tang review 5 sao tu nhom khach vua mua va da xac nhan hai long.",
    progress_percent: 62,
    total_tasks: 9,
    completed_tasks: 5,
    overdue_tasks: 2,
    blocked_tasks: 1,
  },
  {
    id: "ap_sales_vip_callback",
    linked_kpi_id: "kpi_reviews_sales_2026_04",
    title: "Goi lai khach VIP sau giao dich",
    description: "Uu tien goi lai khach co gia tri cao de xin review va xu ly phan hoi som.",
    owner_id: "e4",
    department_id: "d001",
    period,
    status: "active",
    expected_impact_text: "Tang conversion review trong nhom khach gia tri cao.",
    progress_percent: 58,
    total_tasks: 6,
    completed_tasks: 3,
    overdue_tasks: 1,
    blocked_tasks: 0,
  },
  {
    id: "ap_review_request_after_purchase",
    linked_kpi_id: "kpi_reviews_cskh_2026_04",
    title: "Chien dich xin danh gia sau mua thang 4",
    description: "Gui loi moi danh gia den khach da mua hang va co trai nghiem tot.",
    owner_id: "e7",
    department_id: "d004",
    period,
    status: "active",
    expected_impact_text: "Tang so luong review 5 sao tu nhom khach da mua va da nhan hang.",
    progress_percent: 67,
    total_tasks: 12,
    completed_tasks: 8,
    overdue_tasks: 2,
    blocked_tasks: 1,
  },
  {
    id: "ap_followup_no_review",
    linked_kpi_id: "kpi_reviews_cskh_2026_04",
    title: "Follow-up khach chua danh gia",
    description: "Nhac lai cac khach da mua nhung chua de lai review.",
    owner_id: "e7",
    department_id: "d004",
    period,
    status: "active",
    expected_impact_text: "Tang conversion tu nhom khach da nhan hang nhung chua review.",
    progress_percent: 54,
    total_tasks: 8,
    completed_tasks: 4,
    overdue_tasks: 3,
    blocked_tasks: 0,
  },
  {
    id: "ap_low_rating_recovery",
    linked_kpi_id: "kpi_reviews_cskh_2026_04",
    title: "Xu ly khach co nguy co danh gia thap",
    description: "Can thiep som voi khach co dau hieu khong hai long de tranh review xau.",
    owner_id: "e7",
    department_id: "d004",
    period,
    status: "active",
    expected_impact_text: "Giam review xau va tang kha nang chuyen thanh 5 sao.",
    progress_percent: 72,
    total_tasks: 10,
    completed_tasks: 7,
    overdue_tasks: 1,
    blocked_tasks: 1,
  },
  {
    id: "ap_ops_delivery_recovery",
    linked_kpi_id: "kpi_reviews_ops_2026_04",
    title: "Giai quyet don giao tre de bao ve review",
    description: "Ops xu ly som cac don giao tre va cap nhat cho khach truoc khi khach danh gia.",
    owner_id: "e6",
    department_id: "d003",
    period,
    status: "active",
    expected_impact_text: "Giam trai nghiem xau sau giao hang va tang kha nang nhan review 5 sao.",
    progress_percent: 61,
    total_tasks: 7,
    completed_tasks: 4,
    overdue_tasks: 1,
    blocked_tasks: 1,
  },
  {
    id: "ap_sla_shift_coverage",
    linked_kpi_id: "kpi_sla_cskh_2026_04",
    title: "Bao phu ca truc gio cao diem",
    description: "Dieu chinh lich truc va canh bao ton dong de giu SLA phan hoi duoi 5 phut.",
    owner_id: "e7",
    department_id: "d004",
    period,
    status: "active",
    expected_impact_text: "Giam ton dong khung gio cao diem va on dinh toc do phan hoi.",
    progress_percent: 76,
    total_tasks: 7,
    completed_tasks: 5,
    overdue_tasks: 1,
    blocked_tasks: 0,
  },
  {
    id: "ap_sla_fast_reply_playbook",
    linked_kpi_id: "kpi_sla_cskh_2026_04",
    title: "Playbook phan hoi nhanh",
    description: "Chuan hoa template va luong escalate cho cac ticket de phan hoi nhanh hon.",
    owner_id: "e7",
    department_id: "d004",
    period,
    status: "active",
    expected_impact_text: "Tang ty le first reply dung SLA va giam task blocked.",
    progress_percent: 69,
    total_tasks: 5,
    completed_tasks: 3,
    overdue_tasks: 1,
    blocked_tasks: 1,
  },
];

export const executionDemoActionMetrics: ActionMetric[] = [
  {
    id: "metric_sales_qr_invites",
    action_plan_id: "ap_sales_review_request",
    name: "Gui QR review sau mua",
    unit: "customers",
    target: 1_800,
    actual: 1_120,
    completion: 1_120 / 1_800,
    owner_id: "e4",
    assignee_id: "e8",
    status: "yellow",
  },
  {
    id: "metric_sales_vip_calls",
    action_plan_id: "ap_sales_vip_callback",
    name: "Goi lai khach VIP",
    unit: "customers",
    target: 450,
    actual: 260,
    completion: 260 / 450,
    owner_id: "e4",
    assignee_id: "e9",
    status: "yellow",
  },
  {
    id: "metric_review_invites_sent",
    action_plan_id: "ap_review_request_after_purchase",
    name: "Gui loi moi danh gia",
    unit: "customers",
    target: 4_000,
    actual: 2_700,
    completion: 0.675,
    owner_id: "e7",
    assignee_id: "e15",
    status: "yellow",
  },
  {
    id: "metric_followup_pending_review",
    action_plan_id: "ap_followup_no_review",
    name: "Follow-up khach chua danh gia",
    unit: "customers",
    target: 1_000,
    actual: 600,
    completion: 0.6,
    owner_id: "e7",
    assignee_id: "e16",
    status: "yellow",
  },
  {
    id: "metric_vip_call_reviews",
    action_plan_id: "ap_review_request_after_purchase",
    name: "Goi khach VIP xin danh gia",
    unit: "customers",
    target: 300,
    actual: 180,
    completion: 0.6,
    owner_id: "e7",
    assignee_id: "e15",
    status: "yellow",
  },
  {
    id: "metric_low_rating_risk_cases",
    action_plan_id: "ap_low_rating_recovery",
    name: "Xu ly case nguy co danh gia thap",
    unit: "cases",
    target: 100,
    actual: 80,
    completion: 0.8,
    owner_id: "e7",
    assignee_id: "e17",
    status: "yellow",
  },
  {
    id: "metric_ops_risk_shipments",
    action_plan_id: "ap_ops_delivery_recovery",
    name: "Xu ly don giao tre co nguy co review xau",
    unit: "orders",
    target: 180,
    actual: 120,
    completion: 120 / 180,
    owner_id: "e6",
    assignee_id: "e12",
    status: "yellow",
  },
  {
    id: "metric_sla_peak_shifts",
    action_plan_id: "ap_sla_shift_coverage",
    name: "Bao phu ca truc gio cao diem",
    unit: "shifts",
    target: 28,
    actual: 24,
    completion: 24 / 28,
    owner_id: "e7",
    assignee_id: "e15",
    status: "yellow",
  },
  {
    id: "metric_sla_fast_reply",
    action_plan_id: "ap_sla_fast_reply_playbook",
    name: "Cuoc hoi dap first reply duoi 5 phut",
    unit: "conversations",
    target: 1_400,
    actual: 1_260,
    completion: 1_260 / 1_400,
    owner_id: "e7",
    assignee_id: "e16",
    status: "yellow",
  },
];

export const executionDemoEmployeeExecutions: EmployeeExecution[] = [
  {
    employee_id: "e8",
    employee_name: "Nguyen Hai H",
    role: "Senior Sales",
    department_id: "d001",
    linked_kpi_id: "kpi_reviews_sales_2026_04",
    linked_action_plan_id: "ap_sales_review_request",
    assigned_tasks: 5,
    done_tasks: 3,
    overdue_tasks: 1,
    blocked_tasks: 0,
    action_target_name: "Gui QR review sau mua",
    action_target_value: 900,
    action_actual_value: 610,
    action_completion: 610 / 900,
    sla_score: 90,
    quality_score: 87,
    risk_status: "yellow",
  },
  {
    employee_id: "e9",
    employee_name: "Tran Nam I",
    role: "Sales Specialist",
    department_id: "d001",
    linked_kpi_id: "kpi_reviews_sales_2026_04",
    linked_action_plan_id: "ap_sales_vip_callback",
    assigned_tasks: 4,
    done_tasks: 2,
    overdue_tasks: 1,
    blocked_tasks: 0,
    action_target_name: "Goi lai khach VIP",
    action_target_value: 450,
    action_actual_value: 260,
    action_completion: 260 / 450,
    sla_score: 88,
    quality_score: 86,
    risk_status: "yellow",
  },
  {
    employee_id: "e15",
    employee_name: "Nguyen Minh P",
    role: "CSKH",
    department_id: "d004",
    linked_kpi_id: "kpi_reviews_cskh_2026_04",
    linked_action_plan_id: "ap_review_request_after_purchase",
    assigned_tasks: 8,
    done_tasks: 6,
    overdue_tasks: 1,
    blocked_tasks: 0,
    action_target_name: "Gui loi moi danh gia",
    action_target_value: 800,
    action_actual_value: 620,
    action_completion: 0.775,
    sla_score: 92,
    quality_score: 88,
    risk_status: "yellow",
  },
  {
    employee_id: "e16",
    employee_name: "Le Thu Q",
    role: "CSKH",
    department_id: "d004",
    linked_kpi_id: "kpi_reviews_cskh_2026_04",
    linked_action_plan_id: "ap_followup_no_review",
    assigned_tasks: 5,
    done_tasks: 5,
    overdue_tasks: 0,
    blocked_tasks: 0,
    action_target_name: "Follow-up khach chua danh gia",
    action_target_value: 500,
    action_actual_value: 430,
    action_completion: 0.86,
    sla_score: 95,
    quality_score: 91,
    risk_status: "green",
  },
  {
    employee_id: "e17",
    employee_name: "Pham Huy R",
    role: "CSKH",
    department_id: "d004",
    linked_kpi_id: "kpi_reviews_cskh_2026_04",
    linked_action_plan_id: "ap_low_rating_recovery",
    assigned_tasks: 7,
    done_tasks: 2,
    overdue_tasks: 2,
    blocked_tasks: 1,
    action_target_name: "Xu ly case nguy co",
    action_target_value: 100,
    action_actual_value: 45,
    action_completion: 0.45,
    sla_score: 70,
    quality_score: 76,
    risk_status: "red",
  },
  {
    employee_id: "e12",
    employee_name: "Nguyen Lan M",
    role: "Ops Specialist",
    department_id: "d003",
    linked_kpi_id: "kpi_reviews_ops_2026_04",
    linked_action_plan_id: "ap_ops_delivery_recovery",
    assigned_tasks: 4,
    done_tasks: 2,
    overdue_tasks: 1,
    blocked_tasks: 1,
    action_target_name: "Xu ly don giao tre",
    action_target_value: 180,
    action_actual_value: 120,
    action_completion: 120 / 180,
    sla_score: 84,
    quality_score: 82,
    risk_status: "yellow",
  },
  {
    employee_id: "e15",
    employee_name: "Nguyen Minh P",
    role: "CSKH",
    department_id: "d004",
    linked_kpi_id: "kpi_sla_cskh_2026_04",
    linked_action_plan_id: "ap_sla_shift_coverage",
    assigned_tasks: 4,
    done_tasks: 3,
    overdue_tasks: 1,
    blocked_tasks: 0,
    action_target_name: "Bao phu ca truc gio cao diem",
    action_target_value: 14,
    action_actual_value: 12,
    action_completion: 12 / 14,
    sla_score: 93,
    quality_score: 89,
    risk_status: "yellow",
  },
  {
    employee_id: "e16",
    employee_name: "Le Thu Q",
    role: "CSKH",
    department_id: "d004",
    linked_kpi_id: "kpi_sla_cskh_2026_04",
    linked_action_plan_id: "ap_sla_fast_reply_playbook",
    assigned_tasks: 4,
    done_tasks: 3,
    overdue_tasks: 0,
    blocked_tasks: 1,
    action_target_name: "First reply duoi 5 phut",
    action_target_value: 700,
    action_actual_value: 640,
    action_completion: 640 / 700,
    sla_score: 96,
    quality_score: 90,
    risk_status: "green",
  },
];

function mkExecutionTask(input: Task): Task {
  return input;
}

export const executionDemoTasks: Task[] = [
  mkExecutionTask({
    id: "ext1",
    company_id: DEMO_COMPANY_ID,
    title: "Gui QR review cho 450 khach sau mua",
    description: "Loc khach da nhan hang va co dau hieu hai long de gui QR review.",
    assignee_id: "e8",
    reviewer_id: null,
    department_id: "d001",
    project_id: null,
    linked_kpi_id: "kpi_reviews_sales_2026_04",
    linked_action_plan_id: "ap_sales_review_request",
    action_metric_id: "metric_sales_qr_invites",
    priority: "high",
    task_type: "growth",
    status: "in_progress",
    start_date: "2026-04-03",
    due_date: "2026-04-11",
    estimated_hours: 6,
    actual_hours: null,
    action_target_value: 450,
    action_actual_value: 320,
    progress_unit: "customers",
    quality_score: 87,
    sla_score: 90,
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext2",
    company_id: DEMO_COMPANY_ID,
    title: "Goi lai 120 khach VIP khu vuc mien Bac",
    description: "Uu tien nhom VIP co gia tri don hang cao va da xac nhan nhan du hang.",
    assignee_id: "e9",
    reviewer_id: null,
    department_id: "d001",
    project_id: null,
    linked_kpi_id: "kpi_reviews_sales_2026_04",
    linked_action_plan_id: "ap_sales_vip_callback",
    action_metric_id: "metric_sales_vip_calls",
    priority: "high",
    task_type: "growth",
    status: "review",
    start_date: "2026-04-05",
    due_date: "2026-04-12",
    estimated_hours: 5,
    actual_hours: null,
    action_target_value: 120,
    action_actual_value: 74,
    progress_unit: "customers",
    quality_score: 86,
    sla_score: 88,
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext3",
    company_id: DEMO_COMPANY_ID,
    title: "Ra soat script xin review cho team Sales",
    description: "Chuan hoa script review sau mua de tang ti le dong y danh gia.",
    assignee_id: "e4",
    reviewer_id: null,
    department_id: "d001",
    project_id: null,
    linked_kpi_id: "kpi_reviews_sales_2026_04",
    linked_action_plan_id: "ap_sales_review_request",
    action_metric_id: null,
    priority: "normal",
    task_type: "maintenance",
    status: "done",
    start_date: "2026-04-01",
    due_date: "2026-04-08",
    estimated_hours: 2,
    actual_hours: 2,
    action_target_value: 1,
    action_actual_value: 1,
    progress_unit: "task",
    quality_score: 92,
    sla_score: 95,
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext4",
    company_id: DEMO_COMPANY_ID,
    title: "Gui loi moi danh gia cho 300 khach tuan 1",
    description: "Loc danh sach khach da nhan hang, trai nghiem tot, sau do gui loi moi danh gia.",
    assignee_id: "e15",
    reviewer_id: null,
    department_id: "d004",
    project_id: null,
    linked_kpi_id: "kpi_reviews_cskh_2026_04",
    linked_action_plan_id: "ap_review_request_after_purchase",
    action_metric_id: "metric_review_invites_sent",
    priority: "high",
    task_type: "growth",
    status: "in_progress",
    start_date: "2026-04-01",
    due_date: "2026-04-10",
    estimated_hours: 4,
    actual_hours: null,
    action_target_value: 300,
    action_actual_value: 220,
    progress_unit: "customers",
    quality_score: 88,
    sla_score: 92,
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext5",
    company_id: DEMO_COMPANY_ID,
    title: "Follow-up 200 khach chua danh gia tuan 1",
    description: "Nhac lai khach da nhan hang nhung chua de lai review.",
    assignee_id: "e16",
    reviewer_id: null,
    department_id: "d004",
    project_id: null,
    linked_kpi_id: "kpi_reviews_cskh_2026_04",
    linked_action_plan_id: "ap_followup_no_review",
    action_metric_id: "metric_followup_pending_review",
    priority: "high",
    task_type: "growth",
    status: "done",
    start_date: "2026-04-02",
    due_date: "2026-04-09",
    estimated_hours: 4,
    actual_hours: 4,
    action_target_value: 200,
    action_actual_value: 190,
    progress_unit: "customers",
    quality_score: 90,
    sla_score: 96,
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext6",
    company_id: DEMO_COMPANY_ID,
    title: "Goi khach VIP xin danh gia dot 1",
    description: "Uu tien khach VIP da hai long de tang kha nang nhan review 5 sao.",
    assignee_id: "e15",
    reviewer_id: null,
    department_id: "d004",
    project_id: null,
    linked_kpi_id: "kpi_reviews_cskh_2026_04",
    linked_action_plan_id: "ap_review_request_after_purchase",
    action_metric_id: "metric_vip_call_reviews",
    priority: "normal",
    task_type: "growth",
    status: "review",
    start_date: "2026-04-05",
    due_date: "2026-04-12",
    estimated_hours: 3,
    actual_hours: null,
    action_target_value: 80,
    action_actual_value: 55,
    progress_unit: "customers",
    quality_score: 87,
    sla_score: 90,
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext7",
    company_id: DEMO_COMPANY_ID,
    title: "Xu ly 20 case co nguy co danh gia thap",
    description: "Lien he lai cac case co dau hieu khong hai long de xu ly truoc khi khach danh gia.",
    assignee_id: "e17",
    reviewer_id: null,
    department_id: "d004",
    project_id: null,
    linked_kpi_id: "kpi_reviews_cskh_2026_04",
    linked_action_plan_id: "ap_low_rating_recovery",
    action_metric_id: "metric_low_rating_risk_cases",
    priority: "urgent",
    task_type: "urgent",
    status: "blocked",
    start_date: "2026-04-03",
    due_date: "2026-04-11",
    estimated_hours: 6,
    actual_hours: null,
    action_target_value: 20,
    action_actual_value: 9,
    progress_unit: "cases",
    quality_score: 75,
    sla_score: 68,
    blocked_reason: "Dang cho Operations xac nhan phuong an doi tra.",
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext8",
    company_id: DEMO_COMPANY_ID,
    title: "Ra soat template tin nhan xin danh gia",
    description: "Chuan hoa message theo tung nhom khach de tang conversion review.",
    assignee_id: "e7",
    reviewer_id: null,
    department_id: "d004",
    project_id: null,
    linked_kpi_id: "kpi_reviews_cskh_2026_04",
    linked_action_plan_id: "ap_review_request_after_purchase",
    action_metric_id: null,
    priority: "normal",
    task_type: "maintenance",
    status: "done",
    start_date: "2026-04-01",
    due_date: "2026-04-06",
    estimated_hours: 2,
    actual_hours: 2,
    action_target_value: 1,
    action_actual_value: 1,
    progress_unit: "task",
    quality_score: 93,
    sla_score: 95,
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext9",
    company_id: DEMO_COMPANY_ID,
    title: "Phan loai 100 khach chua review theo muc uu tien",
    description: "Phan nhom khach de follow-up dung kich ban va dung thoi diem.",
    assignee_id: "e16",
    reviewer_id: null,
    department_id: "d004",
    project_id: null,
    linked_kpi_id: "kpi_reviews_cskh_2026_04",
    linked_action_plan_id: "ap_followup_no_review",
    action_metric_id: "metric_followup_pending_review",
    priority: "normal",
    task_type: "growth",
    status: "todo",
    start_date: "2026-04-08",
    due_date: "2026-04-14",
    estimated_hours: 3,
    actual_hours: null,
    action_target_value: 100,
    action_actual_value: 0,
    progress_unit: "customers",
    quality_score: 0,
    sla_score: 0,
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext10",
    company_id: DEMO_COMPANY_ID,
    title: "Goi xin loi va cap nhat ETA cho 60 don giao tre",
    description: "Cap nhat ETA cho khach truoc khi phat sinh review xau.",
    assignee_id: "e12",
    reviewer_id: null,
    department_id: "d003",
    project_id: null,
    linked_kpi_id: "kpi_reviews_ops_2026_04",
    linked_action_plan_id: "ap_ops_delivery_recovery",
    action_metric_id: "metric_ops_risk_shipments",
    priority: "high",
    task_type: "growth",
    status: "in_progress",
    start_date: "2026-04-04",
    due_date: "2026-04-13",
    estimated_hours: 5,
    actual_hours: null,
    action_target_value: 60,
    action_actual_value: 38,
    progress_unit: "orders",
    quality_score: 82,
    sla_score: 84,
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext11",
    company_id: DEMO_COMPANY_ID,
    title: "Dong 15 case giao tre can doi tra",
    description: "Xu ly nhung case co nguy co review xau do giao tre va doi tra.",
    assignee_id: "e12",
    reviewer_id: null,
    department_id: "d003",
    project_id: null,
    linked_kpi_id: "kpi_reviews_ops_2026_04",
    linked_action_plan_id: "ap_ops_delivery_recovery",
    action_metric_id: "metric_ops_risk_shipments",
    priority: "urgent",
    task_type: "urgent",
    status: "blocked",
    start_date: "2026-04-06",
    due_date: "2026-04-10",
    estimated_hours: 6,
    actual_hours: null,
    action_target_value: 15,
    action_actual_value: 8,
    progress_unit: "orders",
    quality_score: 80,
    sla_score: 82,
    blocked_reason: "Dang cho kho xac nhan trang thai hang doi.",
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext12",
    company_id: DEMO_COMPANY_ID,
    title: "Phu ca 18h-22h ngay cao diem",
    description: "Can doi lich truc cho team CSKH de giu SLA first reply.",
    assignee_id: "e15",
    reviewer_id: null,
    department_id: "d004",
    project_id: null,
    linked_kpi_id: "kpi_sla_cskh_2026_04",
    linked_action_plan_id: "ap_sla_shift_coverage",
    action_metric_id: "metric_sla_peak_shifts",
    priority: "high",
    task_type: "growth",
    status: "review",
    start_date: "2026-04-07",
    due_date: "2026-04-15",
    estimated_hours: 4,
    actual_hours: null,
    action_target_value: 7,
    action_actual_value: 6,
    progress_unit: "shifts",
    quality_score: 89,
    sla_score: 93,
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext13",
    company_id: DEMO_COMPANY_ID,
    title: "Canh bao ticket qua 3 phut ton dong",
    description: "Bat rule canh bao cho ticket ton dong de tranh tre first reply.",
    assignee_id: "e16",
    reviewer_id: null,
    department_id: "d004",
    project_id: null,
    linked_kpi_id: "kpi_sla_cskh_2026_04",
    linked_action_plan_id: "ap_sla_fast_reply_playbook",
    action_metric_id: "metric_sla_fast_reply",
    priority: "normal",
    task_type: "maintenance",
    status: "done",
    start_date: "2026-04-02",
    due_date: "2026-04-09",
    estimated_hours: 2,
    actual_hours: 2,
    action_target_value: 350,
    action_actual_value: 330,
    progress_unit: "conversations",
    quality_score: 92,
    sla_score: 96,
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
  mkExecutionTask({
    id: "ext14",
    company_id: DEMO_COMPANY_ID,
    title: "Cap nhat template first reply cho 5 nhom ticket",
    description: "Rut gon thao tac phan hoi dau de cai thien SLA.",
    assignee_id: "e7",
    reviewer_id: null,
    department_id: "d004",
    project_id: null,
    linked_kpi_id: "kpi_sla_cskh_2026_04",
    linked_action_plan_id: "ap_sla_fast_reply_playbook",
    action_metric_id: null,
    priority: "normal",
    task_type: "maintenance",
    status: "todo",
    start_date: "2026-04-09",
    due_date: "2026-04-16",
    estimated_hours: 3,
    actual_hours: null,
    action_target_value: 5,
    action_actual_value: 3,
    progress_unit: "templates",
    quality_score: 0,
    sla_score: 0,
    sprint_id: null,
    story_points: null,
    parent_task_id: null,
  }),
];

function genId(prefix: string) {
  return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`;
}

function statusByCompletion(completionRate: number): "green" | "yellow" | "red" {
  if (completionRate >= 0.85) return "green";
  if (completionRate >= 0.6) return "yellow";
  return "red";
}

function upsertTarget(kpiId: string, nextPeriod: string, targetValue?: number) {
  if (targetValue == null || Number.isNaN(targetValue)) return;
  const idx = executionDemoKpiTargets.findIndex((row) => row.kpi_id === kpiId && row.period === nextPeriod);
  const next = { kpi_id: kpiId, period: nextPeriod, target_value: targetValue };
  if (idx >= 0) executionDemoKpiTargets[idx] = next;
  else executionDemoKpiTargets.push(next);
}

function upsertActual(kpiId: string, nextPeriod: string, actualValue: number) {
  const target = executionDemoKpiTargets.find((row) => row.kpi_id === kpiId && row.period === nextPeriod)?.target_value ?? 0;
  const completionRate = target > 0 ? actualValue / target : 0;
  const status = statusByCompletion(completionRate);
  const next = { kpi_id: kpiId, period: nextPeriod, actual_value: actualValue, completion_rate: completionRate, status };
  const idx = executionDemoKpiActuals.findIndex((row) => row.kpi_id === kpiId && row.period === nextPeriod);
  if (idx >= 0) executionDemoKpiActuals[idx] = next;
  else executionDemoKpiActuals.push(next);

  const resultIdx = executionDemoDepartmentResultKpis.findIndex((row) => row.id === kpiId && row.period === nextPeriod);
  if (resultIdx >= 0) {
    executionDemoDepartmentResultKpis[resultIdx] = {
      ...executionDemoDepartmentResultKpis[resultIdx],
      actual: actualValue,
      target,
      status,
      last_updated_at: new Date().toISOString(),
    };
  }
}

function ensureDepartmentResultKpi(kpi: Kpi, nextPeriod: string, targetValue?: number) {
  if (kpi.level !== "department" || !kpi.owner_department_id) return;
  const department = demoDepartments.find((dept) => dept.id === kpi.owner_department_id);
  const target =
    targetValue ??
    executionDemoKpiTargets.find((row) => row.kpi_id === kpi.id && row.period === nextPeriod)?.target_value ??
    0;
  const actual =
    executionDemoKpiActuals.find((row) => row.kpi_id === kpi.id && row.period === nextPeriod)?.actual_value ??
    0;
  const completionRate = target > 0 ? actual / target : 0;
  const next: DepartmentResultKpi = {
    id: kpi.id,
    name: kpi.name,
    department_id: kpi.owner_department_id,
    department_name: department?.name ?? "Department",
    period: nextPeriod,
    type: "result_kpi",
    unit: kpi.unit,
    target,
    actual,
    data_source: kpi.data_source ?? "manual_import",
    rollup_mode: "manual",
    status: statusByCompletion(completionRate),
    days_left: 10,
    last_updated_at: new Date().toISOString(),
  };
  const idx = executionDemoDepartmentResultKpis.findIndex((row) => row.id === kpi.id && row.period === nextPeriod);
  if (idx >= 0) executionDemoDepartmentResultKpis[idx] = { ...executionDemoDepartmentResultKpis[idx], ...next };
  else executionDemoDepartmentResultKpis.push(next);
}

export function upsertExecutionDemoKpi(input: {
  id?: string;
  companyId?: string;
  name: string;
  code?: string;
  level: Kpi["level"];
  unit: string;
  targetFrequency: Kpi["target_frequency"];
  parentKpiId?: string | null;
  ownerDepartmentId?: string | null;
  ownerEmployeeId?: string | null;
  weight?: number;
  active?: boolean;
  targetValue?: number;
  period?: string;
}) {
  const nextPeriod = input.period || period;
  const id = input.id || genId("kpi");
  const existing = executionDemoKpis.find((row) => row.id === id);
  const next: Kpi = {
    ...(existing ?? {
      id,
      company_id: input.companyId || DEMO_COMPANY_ID,
      description: "Demo Result KPI. Actual lay tu import/manual, khong cong tu task.",
      owner_team_id: null,
      data_source: "manual_import",
      calc_mode: "manual",
    }),
    id,
    company_id: input.companyId || existing?.company_id || DEMO_COMPANY_ID,
    name: input.name,
    code: input.code || null,
    level: input.level,
    unit: input.unit || "%",
    target_frequency: input.targetFrequency,
    parent_kpi_id: input.parentKpiId || null,
    owner_department_id: input.ownerDepartmentId || null,
    owner_employee_id: input.ownerEmployeeId || null,
    weight: input.weight ?? existing?.weight ?? 1,
    active: input.active ?? existing?.active ?? true,
  };

  const idx = executionDemoKpis.findIndex((row) => row.id === id);
  if (idx >= 0) executionDemoKpis[idx] = next;
  else executionDemoKpis.push(next);

  upsertTarget(id, nextPeriod, input.targetValue);
  ensureDepartmentResultKpi(next, nextPeriod, input.targetValue);
  return id;
}

export function recordExecutionDemoKpiActual(input: { kpiId: string; period: string; actualValue: number }) {
  upsertActual(input.kpiId, input.period, input.actualValue);
}

export function deactivateExecutionDemoKpi(id: string) {
  const idx = executionDemoKpis.findIndex((row) => row.id === id);
  if (idx >= 0) executionDemoKpis[idx] = { ...executionDemoKpis[idx], active: false };
}

export function upsertExecutionDemoActionPlan(input: {
  id?: string;
  linkedKpiId: string;
  title: string;
  description?: string;
  ownerId?: string;
  departmentId?: string;
  period?: string;
  status?: ActionPlan["status"];
  expectedImpactText?: string;
  progressPercent?: number;
}) {
  const id = input.id || genId("ap");
  const existing = executionDemoActionPlans.find((row) => row.id === id);
  const linkedKpi = executionDemoKpis.find((row) => row.id === input.linkedKpiId);
  const next: ActionPlan = {
    id,
    linked_kpi_id: input.linkedKpiId,
    title: input.title,
    description: input.description ?? existing?.description ?? "",
    owner_id: input.ownerId || existing?.owner_id || linkedKpi?.owner_employee_id || "e7",
    department_id: input.departmentId || existing?.department_id || linkedKpi?.owner_department_id || "d004",
    period: input.period || existing?.period || period,
    status: input.status || existing?.status || "active",
    expected_impact_text: input.expectedImpactText ?? existing?.expected_impact_text ?? "",
    progress_percent: input.progressPercent ?? existing?.progress_percent ?? 0,
    total_tasks: existing?.total_tasks ?? 0,
    completed_tasks: existing?.completed_tasks ?? 0,
    overdue_tasks: existing?.overdue_tasks ?? 0,
    blocked_tasks: existing?.blocked_tasks ?? 0,
  };
  const idx = executionDemoActionPlans.findIndex((row) => row.id === id);
  if (idx >= 0) executionDemoActionPlans[idx] = next;
  else executionDemoActionPlans.push(next);
  return id;
}

// Keep the KPI sandbox empty by default so users can build the tree by hand.
// The mutation helpers above will repopulate these arrays during the test session.
executionDemoKpis.length = 0;
executionDemoKpiTargets.length = 0;
executionDemoKpiActuals.length = 0;
executionDemoKpiFormulas.length = 0;
executionDemoDepartmentResultKpis.length = 0;
executionDemoActionPlans.length = 0;
executionDemoActionMetrics.length = 0;
executionDemoEmployeeExecutions.length = 0;
executionDemoTasks.length = 0;
